@switch($method_id)
    @case(1)
        <th>Icumsa</th>
        <th>Moist</th>
        <th>Brix</th>
        <th>Pol</th>
        <th>HK</th>
        <th>SO<sub>2</sub></th>
        <th>BJB</th>
        @break
    @default
        @break
@endswitch
